---
collections:
  - name: community.general
    version: 7.2.1
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.4
roles:
  - src: xanmanning.k3s
    version: v3.4.2
