---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./scrutiny/ks.yaml
  - ./uptime-kuma/ks.yaml
  - ./prometheus/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./goldilocks/ks.yaml
