---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: &app gmvitabot
  namespace: telegram
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
    external-dns/is-public: "true"
spec:
  ingressClassName: external
  rules:
    - host: "botstelegram.${SECRET_DOMAIN}"
      http:
        paths:
          - path: "/${SECRET_KINDLEBOT_TOKEN}/"
            pathType: Prefix
            backend:
              service:
                name: gmvitabot
                port:
                  number: 8080
  tls:
    - hosts:
        - "botstelegram.${SECRET_DOMAIN}"
