---
apiVersion: v1
kind: Service
metadata:
  name: &app gmvitabot
  namespace: telegram
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
spec:
  selector:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  ports:
    - protocol: TCP
      name: gmvitabot
      port: 8080
      targetPort: 8080
