---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./nextcloud/ks.yaml
  - ./congatudo/ks.yaml
  - ./adguard/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./home-assistant/ks.yaml
